# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d0c424cd-818a-41dd-9bdd-0a5bb5542156";
      fsType = "ext4";
    };


  boot.initrd.luks.devices."luks-94d8c659-dfb3-4b54-a457-4b703760a701".device = "/dev/disk/by-uuid/94d8c659-dfb3-4b54-a457-4b703760a701";
  boot.initrd.luks.devices."luks-2ecd7276-d4a8-4324-ab9c-ca12e8f99dc4".device = "/dev/disk/by-uuid/2ecd7276-d4a8-4324-ab9c-ca12e8f99dc4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/680C-1868";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/029edeaa-6f7d-4cb6-810b-8bac50ab01dd"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
